spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:47.101.138.250}:${DATASOURCE_PORT:3306}/sc_admin?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:123456}
    # rabbitmq
  rabbitmq:
    host: ${RABBIT_MQ_HOST:47.101.138.250}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  # redis
  redis:
    host: ${REDIS_HOST:47.101.138.250}
    port: ${REDIS_PORT:6379}
    lettuce:
      pool:
        max-active: 300

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hidePackages: com.hibase.hibasedesign
  local:
    # 短時本地緩存，主要用于要求时效较高的配置
    default:
      type: caffeine
      keyConvertor: fastjson
      expireAfterWriteInMillis: 60000
      expireAfterAccessInMillis: 40000

